export const CATEGORIES_MAP = {
  GENERAL_KNOWLEDGE: "9",
  MYTHOLOGY: "20",
  MUSIC: "12",
  FILM: "11",
  SPORTS: "21",
  ART: "25",
  MUSICAL_AND_THEATRES: "13",
  TELEVISION: "14",
  VIDEO_GAMES: "15",
  BOARD_GAMES: "16",
  SCIENCE_NATURE: "17",
  SCIENCE_COMPUTERS: "18",
  SCIENCE_MATH: "19",
  GEOGRAPHY: "22",
  HISTORY: "23",
  CELEBRITIES: "26",
  LOCATION: "10000",
  VEHICLES: "28",
};

export const AVATAR_NAME_TO_PATH = {

}
